name: lemon_tv
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  video_player: ^2.9.3
  smooth_page_indicator: ^1.0.0
  shared_preferences: ^2.0.15
  auto_size_text: ^3.0.0
  http: ^1.2.0
  screen_brightness: ^2.1.2
  fluttertoast: ^8.2.12
  xml: ^6.3.0
  html: ^0.15.4
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  expandable: ^5.0.1
  punycode: ^1.0.0
  json_annotation: ^4.7.0
  punycode_converter: ^0.2.1
  encrypt: ^5.0.1
  battery_plus: ^6.2.1
  intl: ^0.20.2
  json5: ^0.8.2
  path_provider: ^2.1.5
  flutter_vlc_player: ^7.4.2

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

