name: lemon_tv
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+101

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  video_player: ^2.9.3
  smooth_page_indicator: ^1.0.0
  shared_preferences: ^2.5.3
  auto_size_text: ^3.0.0
  http: ^1.2.0
  screen_brightness: ^2.0.0
  fluttertoast: ^8.2.12
  xml: ^6.3.0
  html: ^0.15.4
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  expandable: ^5.0.1
  punycode: ^1.0.0
  json_annotation: ^4.7.0
  punycode_converter: ^0.2.1
  encrypt: ^5.0.1
  battery_plus: ^6.2.1
  intl: ^0.20.2
  json5: ^0.8.2
  path_provider: ^2.1.5
  path: ^1.8.3
#  flutter_vlc_player: ^7.4.2
  get: ^4.7.2
  photo_manager: ^3.4.4
  permission_handler: ^11.4.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  adaptive_action_sheet: ^2.0.4
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.16
  audio_session: ^0.1.10
  audio_service: ^0.18.18
  scrollable_positioned_list: ^0.3.5
  provider: ^6.1.1
  marquee: ^2.2.3
  speech_to_text: ^7.0.0
#  ffmpeg_kit_flutter_new: ^1.3.0
  wakelock_plus: ^1.3.2
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  video_player_media_kit: ^1.0.6
  media_kit_libs_android_video: any
  media_kit_libs_ios_video: any
  media_kit_libs_macos_video: any
  media_kit_libs_windows_video: any



dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  launcher_name: ^1.0.2
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/music/
    - assets/sounds/begin_record.mp3
    - assets/app_icon.png
    - assets/ssl/
launcher_name:
  default: "LM_SQPlayer"
#  dart run launcher_name:main

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # 你的图标路径
#  插件会自动生成所有尺寸的图标：
#  flutter pub run flutter_launcher_icons:main


